### ISSUE TITLE
Can't launch it... [Windows subsystem for Linux]

### ISSUE THREAD

**Issue by Kronophage** [manuelruder/fast-artistic-videos#11]
Hi!
First of all, I'm sorry to ask help for something as basic as this!
I'm on windows, and I've install all dependencies needed, in order to make this project work, but my lack of knowledge on shell make it really hard for me to understand what goes wrong.

I tried all sort of commands variations on my command prompt, but each time, the result is :

styleVideo_*.sh: ${filename//[%]/x}: bad substitution

Usually, the command I enter is something like this :

sh stylizeVideo_deepflow.sh ./resources/input.mp4 ./models/checkpoint-mosaic-video.t7

This syntaxe is really terrifying for me, I don't understand what did I do wrong, and I my internet research didn't helped me...
I tried to edit the code, and assign myself the value of filename, but other errors comes up. I really have problems with the shell :/

I hope you can help me, really want to test your amazing work!
Thank you! :)

**Comment by manuelruder** [comment]
I don't really know much about the Windows subsystem for Linux, but you could try `bash stylizeVideo_deepflow.sh ...`. The scripts were written with bash syntax,

**Comment by Kronophage** [comment]
Wow! Didn't expected an answer this fast! 
However, I had already tried this, and it produce the same result.

The problem comes from the second variable that I give, the path_to_pretrained_model.

When I just enter `bash stylizeVideo_deepflow.sh` or `bash stylizeVideo_deepflow.sh ./resources/input.mp4`, your code remind me this : 

`Usage: ./stylizeVideo.sh <path_to_video> <path_to_pretrained_model>`

It's only when I try the full command : 

`bash stylizeVideo_deepflow.sh ./resources/input.mp4 ./models/checkpoint-mosaic-video.t7`

That I've the previous error : 
 
`stylizeVideo_deepflow.sh: ${filename//[%]/x}: bad substitution`

I'm so sorry to bother you with unimportant stuff like that. Could you certify me that the syntaxe of my path to pretrained model is correct?

**Comment by manuelruder** [comment]
hmm, then bash in Windows subsystem for Linux may not support this syntax. I never had any problems with this on Ubuntu machines.
Note that you can always replace the argument parsing with hard coded values, i.e. `filename=input` and `extension=mp4`.
But given that it already fails on such an early stage in the script, there could be even more errors later and you could be better off by just installing Ubuntu as a second operating system.

**Comment by Kronophage** [comment]
Effectively, I have more bug when I enter values manually...
Many thanks for your patience :)

I don't understand why it's easy to find many resources to image style transfer on window, but it's just impossible to find a good model of video style transfer...

Anyway, I will try again later, when I will have Ubuntu.

Thanks again, friendly man!
