### ISSUE TITLE
make_video_dataset.py Exception in thread Thread-3

### ISSUE THREAD

**Issue by itsKaspar** [manuelruder/fast-artistic-videos#15]
hi,

I've successively cut up the dataset and computed optical flow + occlusion 
and am currently trying to make the h5 file.

I started running :

`python video_dataset/make_video_dataset.py --input_dir /mnt/08E0B3C06558415B/neural/hollywood_flowlist/ --sequence_length 1`

and got a few issues with the "queue" model that couldn't be found so I added this to the code :

```
try: 
    import queue as Queue
    import queue as queue
except ImportError:
    import Queue as Queue
    import Queue as queue
```
and then got TypeErrors of the type :

```
Found 9291 images
Traceback (most recent call last):
  File "video_dataset/make_video_dataset.py", line 160, in <module>
    add_data(f, args.input_dir, 'train', args)
  File "video_dataset/make_video_dataset.py", line 87, in add_data
    input_queue = Queue()
TypeError: 'module' object is not callable
```
that I tried fixing by adding "queue." to every call of Queue()

```
  # input_queue stores (idx, filename) tuples,
  # output_queue stores (idx, resized_img) tuples
  input_queue = queue.Queue()
  output_queue = queue.Queue()
```

But now, wether using python2.7 or python 3.5 to run the script,
I get the following output which is similar to another issue #12 for which the solution did not work for me

```
Found 9291 images
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "video_dataset/make_video_dataset.py", line 121, in write_worker
    flow_dset[idx,i] = flow.transpose(2, 0, 1)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/kaspar/.local/lib/python3.5/site-packages/h5py/_hl/dataset.py", line 609, in __setitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/kaspar/.local/lib/python3.5/site-packages/h5py/_hl/selections.py", line 94, in select
    sel[args]
  File "/home/kaspar/.local/lib/python3.5/site-packages/h5py/_hl/selections.py", line 261, in __getitem__
    start, count, step, scalar = _handle_simple(self.shape,args)
  File "/home/kaspar/.local/lib/python3.5/site-packages/h5py/_hl/selections.py", line 451, in _handle_simple
    x,y,z = _translate_int(int(arg), length)
  File "/home/kaspar/.local/lib/python3.5/site-packages/h5py/_hl/selections.py", line 471, in _translate_int
    raise ValueError("Index (%s) out of range (0-%s)" % (exp, length-1))
ValueError: Index (0) out of range (0--1)

```
Thank you for your help :)

**Comment by manuelruder** [comment]
There must be an issue with the following line:
`flow_dset = h5_file.create_dataset(dset_flow_name, dset_size2, np.float32)`
it has created an empty dataset. Your error message is telling that length=0 for the dataset `flow_dset` and therefore it cannot insert any data. This is quite strange.

If the module "queue" isn't found, this indicates that you are using python 2.x. In python 2.x, this module was called "Queue" (upper case). Try to explicitly call python3 with `python3 video_dataset/make_video_dataset.py ...` and remove your queue workaround. It should not be necessary if everything is set up properly on your system.

**Comment by itsKaspar** [comment]
thx, I took out the Queue workarounds.

I gather the minimum --sequence_length must be 2,
else the flow_dset will be empty

```
dset_size2 = (num_images, args.sequence_length-1, 2, args.height, args.width)
flow_dset = h5_file.create_dataset(dset_flow_name, dset_size2, np.float32)
```

whereas I computed my flow list with 

```
<num_tuples_per_scene> 1
<num_frames_per_tuble> 2
```
for a really minimal dataset

**Comment by manuelruder** [comment]
Ah yes, I didn't pay attention to this.

`sequence_length` must be at least 2 and it should equal `num_frames_per_tuble`, not `num_tuples_per_scene`.

I noticed that this is wrong in my description. I will change this.

Hint: if you can afford a little extra computation, I would set num_frames_per_tuble to 3 so you can use the multi-frame training procedure with at least one additional frame. Multi-frame was a big quality improvement.

**Comment by itsKaspar** [comment]
thanks for the clarification and the hint ! 

I'm currently re-computing for num_frames_per_tuble to 2 
I'll try and compute for 3 when I will have managed to pull something off but it might take me a few weeks of heating my room with my computer before this all finishes :dancer:
