### ISSUE TITLE
High Resolution Stylized Videos

### ISSUE THREAD

**Issue by noufpy** [manuelruder/fast-artistic-videos#16]
Hello again!

So I've produced many stylized videos with your model but I would love to take it to the next level and have super high quality resolution, say around 4000 pixels in width. I've been getting strange errors when I attempt to do this: 

<img width="446" alt="screen shot 2018-12-11 at 11 07 18 am" src="https://user-images.githubusercontent.com/22034616/49813235-04c65180-fd35-11e8-81ed-c2656fa909f7.png">

Have you attempted to produce a video of this high resolution? If so, how did you attempt to do so?
and any ideas what this error might mean? It does not seem to be a memory issue.. 

Machine Specs: Linux (Ubuntu 16.04), Quadro P6000, GPU 24 GB, RAM 30 GB, CPUS 8

**Comment by manuelruder** [comment]
It's a flownet2 issue. It cannot process such large input images.

But even if you could proceed with flownet2 you would have two additional problems:
1) such a high resolution might produce out of memory error in the actual style transfer model
2) even if you somehow managed to do so by a super high-end 32GB GPU, the result might not look that good. The style is always applied at the same pixel scale so if you increase pixel density you will have very tiny style elements in the image. To fix this you'd need to implement additional methods like a multi scale architecture
