### ISSUE TITLE
Skip pre-computed *flo ?

### ISSUE THREAD

**Issue by AIaesthetic** [manuelruder/fast-artistic-videos#17]
Hi, Thank you for this amazing code.

I ran it without any problems, It's just I'm wondering if it's possible to skip re-computing `.flo` files if they already present. I think deepflow can skip them, but when running on flownet2 I have to re-compute the whole flo thing.

**Comment by manuelruder** [comment]
[I thought it does?](https://github.com/manuelruder/fast-artistic-videos/blob/master/makeOptFlow_flownet.sh#L46)

Can you check if flow_list.txt [gets cleared](https://github.com/manuelruder/fast-artistic-videos/blob/master/makeOptFlow_flownet.sh#L39) properly? Do you use any special characters or white spaces in your path?

**Comment by AIaesthetic** [comment]
my bad. I did some tweaks to the script and I didn't give attention to the ` if [[ ! -f ${folderName}/forward_${j}_${i}.flo ]]`  [#L46](https://github.com/manuelruder/fast-artistic-videos/blob/master/makeOptFlow_flownet.sh#L46) everything is working great now.
