### ISSUE TITLE
Does anyone already computed flow for training ?

### ISSUE THREAD

**Issue by AIaesthetic** [manuelruder/fast-artistic-videos#19]
I'm wondering if anyone with good computer specs, finished the optical flow process, and won't mind to share it with me. I see that it's impossible for me to compute the flow of Hollywood2 dataset on my gtx1060. I can survive the training thing, but to compute the flow on my computer is a piece of craziness. So, if anyone that could share his `.flo` output files. It will be a the greatest Christmas gift I can ever get. 
my email is bouaadii@gmail.com

**Comment by manuelruder** [comment]
There is already a thread for this, #13
