### ISSUE TITLE
Model compatibility

### ISSUE THREAD

**Issue by jbgrant01** [manuelruder/fast-artistic-videos#2]
Is it possible to use models trained from Justin Johnson's fast-neural-style code?

**Comment by manuelruder** [comment]
No, this is not possible. The models are specifically trained for temporal consistency.

**Comment by jbgrant01** [comment]
Thanks. Any ETA for the training modules?

**Comment by manuelruder** [comment]
Our work is still part of an ongoing paper submission. We will release the code once the paper is regularly published. No ETA, but probably still this spring.

**Comment by jbgrant01** [comment]
Great. I look forward to seeing it as well as reading the new paper.

**Comment by manuelruder** [comment]
The source code for training is now released. Unfortunately, we had a hard drive failure in the meantime, and I had to rewrite some of the preprocessing steps, which is also the reason why it took so long.
There could also be some issues remaining due to the rewrite, let me know if any.
