### ISSUE TITLE
Spherical Video Training 

### ISSUE THREAD

**Issue by noufpy** [manuelruder/fast-artistic-videos#22]
Hi Manuel, I ran into an issue regarding training for spherical videos. Your instructions say: first train a video model and then finetune it. I attempted this with several trained video models that I have but I kept getting this error (relating to the data_mix parameter): 

![Screen Shot 2019-03-13 at 1 29 08 PM](https://user-images.githubusercontent.com/22034616/54300812-09004600-4594-11e9-9d83-58b961c79b15.png)

I tried different variations for the data_mix parameter but no matter what.. that "vr:<n>" was giving me issues. Any thoughts on the matter?

Thank you for your help in advance!

**Comment by noufpy** [comment]
Still looking for help on this! Would really appreciate any help/guidance. I am very stuck :)

**Comment by manuelruder** [comment]
There was an issue that function names didn't match. I corrected it. Thanks for reporting.
