### ISSUE TITLE
stylizeVideo_deepflow.sh computes all .flo and .pgm but does not output images

### ISSUE THREAD

**Issue by ynnckstrm** [manuelruder/fast-artistic-videos#29]
Hi, thanks for the amazing code first off all!
However I'm running in some problems with the usage. When I start stylizeVideo_deepflow.sh like this (everything set on default):

`bash ./stylizeVideo_deepflow.sh fra_converted.m4v models/checkpoint-schlief-video.t7 models/checkpoint-schlief-image.t7 `

It outputs the following:

`Starting optical flow computation as a background task...
Starting video stylization...
./fra_converted/flow_default/reliable_2_1.pgm./fra_converted/flow_default/reliable_1_2.pgmModel loaded.	
Model loaded.	
Elapsed time for stylizing frame independently:0.825891	
Writing output image to fra_converted/out-00001.png	
/home/yannick/torch/install/bin/luajit: ./fast_artistic_video/utils.lua:143: attempt to call field 'BilinearSamplerBDHW' (a nil value)
stack traceback:
	./fast_artistic_video/utils.lua:143: in function 'warp_image'
	fast_artistic_video.lua:156: in function 'func_make_last_frame_warped'
	./fast_artistic_video_core.lua:162: in function 'run_next_image'
	./fast_artistic_video_core.lua:208: in function 'run_fast_neural_video'
	fast_artistic_video.lua:187: in function 'main'
	fast_artistic_video.lua:192: in main chunk
	[C]: in function 'dofile'
	...nick/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x55eda0826570`

Then it starts to compute the OpticalFlow files in "/flow_default" but only outputs one image. After completing to compute all OpticalFlow files, it does nothing.

I am running Ubuntu 18.04, CUDA10.1, cudnn and the modified torch version by nagadomi.
Does anyone have an idea why this happens? Thank you a lot in advance!

Sorry if I forgot any details.

**Comment by ynnckstrm** [comment]
I started using `fast_artistic_videos.lua` instead of `stylizeVideo_deepflow.sh`
Now it works! Something I did not find in the description is that creating the individual frames, optical flow files and the output images are separate tasks, that `stylizeVideo_deepflow.sh` just does for you.

**For any beginners like me**, I'm using the following command to create individual frames from the original video:

`ffmpeg -i yourvideo.mp4 fra/fra_%04d.png`

This to create the optical flow:

`bash makeOptFlow_deepflow.sh ./fra/fra_%04d.png ./fra/flow 1 1`
_`fra` is the name of the folder I'm outputting_ 

This to create the output images:

`th ./fast_artistic_video.lua -model_vid ./models/checkpoint-schlief-video.t7 -model_img ./models/checkpoint-schlief-image.t7 -input_pattern fra/fra_%04d.png -flow_pattern ./fra/flow/backward_[%d]_{%d}.flo -occlusions_pattern ./fra/flow/reliable_[%d]_{%d}.pgm -output_prefix stylized/out -gpu 0`

You can run the optical flow creation and image creation simultaneously.

I'm very very happy with results it produces and the speed! Thank you @manuelruder for this amazing program!

**Comment by gateway** [comment]
what you do with audio?

**Comment by ynnckstrm** [comment]
@gateway This repo doesn't compute audio, just video
