### ISSUE TITLE
Problem installing stnbdhw

### ISSUE THREAD

**Issue by jbgrant01** [manuelruder/fast-artistic-videos#3]
I changed the FIND_PACKAGE to CUDA 9.1, and bumped the "-arch=sm_20" to sm_30. I get errors saying removing non-existant packages for the THC modules, but they are in home/jim/torch/install/include/THC/generic/. It looks like things are compiling and installing, but the test.lua and init.lua for stn aren't to be found. I think the error message when starting the video stylization is "No LuaRocks module found for stn.test"

Everything else seems to be installed and working. Any help would be appreciated.

**Comment by manuelruder** [comment]
In the file init.lua remove the line "require('stn.test')". Does this solve the issue?

**Comment by jbgrant01** [comment]
Yes, it fixed that problem. Now to get my cudnn to work. Not your issue.

Thanks for the help.
