### ISSUE TITLE
./consistencyChecker/consistencyChecker: No such file or directory

### ISSUE THREAD

**Issue by agilebean** [manuelruder/fast-artistic-videos#4]
Can anybody help me here? Would be *really* happy, as I have been desperately trying to get this great tool running...
I'm on Ubuntu 16.04 LTS.

Trying

`bash stylizeVideo_deepflow.sh ../videos/short.mp4 ./models/checkpoint-mosaic-image.t7`

gave me the only error message that keeps coming every 10s:
`makeOptFlow_deepflow.sh: line 59: ./consistencyChecker/consistencyChecker: No such file or directory
makeOptFlow_deepflow.sh: line 60: ./consistencyChecker/consistencyChecker: No such file or directory
makeOptFlow_deepflow.sh: line 59: ./consistencyChecker/consistencyChecker: No such file or directory
makeOptFlow_deepflow.sh: line 60: ./consistencyChecker/consistencyChecker: No such file or directory
makeOptFlow_deepflow.sh: line 59: ./consistencyChecker/consistencyChecker: No such file or directory
makeOptFlow_deepflow.sh: line 60: ./consistencyChecker/consistencyChecker: No such file or directory
...
`
Why is this happening although the consistencyChecker does exist at that path, and how can I stop the recurring error message (CRL+C doesn't help)?

**Comment by manuelruder** [comment]
Are the video files extracted correctly, i.e. is there a folder "short" with "frame_0001.ppm" etc.? And is there a folder "flow_<resolution>" inside that folder with .flo files? I could be that the optical flow was not calculated correctly.
By the way, the second argument should be the _video_ model.

**Comment by agilebean** [comment]
Yes, the folder was generated and contained the flow_ files.
And you're right, I pasted the wing command but I did use the video model.

After reinstalling boost, cunn and stnbhwd, I got a little further in the script. The frame_xxxx.ppm files and the backward_x_x.flo files are generated.
And...
only 1 output file named "out-00001.png"!
Again, the consistencerChecker seems to remain the root cause, and the makeOptFlow_deepflow.sh script doesn't stop. 
Is there any cure for this?

Here's the output:

Hello,

```
 libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '../videos/2018-04-01rudy-dancing-short.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp41mp42isom
    creation_time   : 2018-04-02T09:30:24.000000Z
  Duration: 00:00:01.30, start: -0.017778, bitrate: 2801 kb/s
    Stream #0:0(und): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 268x480, 2301 kb/s, 30 fps, 30 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      creation_time   : 2018-04-02T09:30:24.000000Z
      handler_name    : Core Media Video
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 67 kb/s (default)
    Metadata:
      creation_time   : 2018-04-02T09:30:24.000000Z
      handler_name    : Core Media Audio
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> ppm (native))
Press [q] to stop, [?] for help
Output #0, image2, to '2018-04-01rudy-dancing-short/frame_%05d.ppm':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp41mp42isom
    encoder         : Lavf57.83.100
    Stream #0:0(und): Video: ppm, rgb24, 268x480, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      creation_time   : 2018-04-02T09:30:24.000000Z
      handler_name    : Core Media Video
      encoder         : Lavc57.107.100 ppm
frame=   40 fps=0.9 q=-0.0 Lsize=N/A time=00:00:01.33 bitrate=N/A dup=1 drop=0 speed=0.0286x
video:15076kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

Starting optical flow computation as a background task...
Starting video stylization...
makeOptFlow_deepflow.sh: line 59: ./consistencyChecker/consistencyChecker: No such file or directory
makeOptFlow_deepflow.sh: line 60: ./consistencyChecker/consistencyChecker: No such file or directory
Model loaded.
Elapsed time for stylizing frame independently:0.771224
Writing output image to 2018-04-01rudy-dancing-short/out-00001.png
Waiting for file "2018-04-01rudy-dancing-short/flow_default/reliable_2_1.pgm"
makeOptFlow_deepflow.sh: line 59: ./consistencyChecker/consistencyChecker: No such file or directory
makeOptFlow_deepflow.sh: line 60: ./consistencyChecker/consistencyChecker: No such file or directory


makeOptFlow_deepflow.sh: line 59: ./consistencyChecker/consistencyChecker: No such file or directory
makeOptFlow_deepflow.sh: line 60: ./consistencyChecker/consistencyChecker: No such file or directory
makeOptFlow_deepflow.sh: line 59: ./consistencyChecker/consistencyChecker: No such file or directory
makeOptFlow_deepflow.sh: line 60: ./consistencyChecker/consistencyChecker: No such file or directory
makeOptFlow_deepflow.sh: line 59: ./consistencyChecker/consistencyChecker: No such file or directory
makeOptFlow_deepflow.sh: line 60: ./consistencyChecker/consistencyChecker: No such file or directory
makeOptFlow_deepflow.sh: line 59: ./consistencyChecker/consistencyChecker: No such file or directory
makeOptFlow_deepflow.sh: line 60: ./consistencyChecker/consistencyChecker: No such file or directory
makeOptFlow_deepflow.sh: line 59: ./consistencyChecker/consistencyChecker: No such file or directory
makeOptFlow_deepflow.sh: line 60: ./consistencyChecker/consistencyChecker: No such file or directory
makeOptFlow_deepflow.sh: line 59: ./consistencyChecker/consistencyChecker: No such file or directory
```

Root cause for the repeating output maybe the wait function as seen in the stack when the script is stopped:

```
stack traceback:
	[C]: in function 'execute'
	./fast_artistic_video/utils.lua:77: in function 'wait_for_file'
	fast_artistic_video.lua:102: in function 'func_load_cert'
	./fast_artistic_video_core.lua:206: in function 'run_fast_neural_video'
	fast_artistic_video.lua:187: in function 'main'
	fast_artistic_video.lua:192: in main chunk
	[C]: in function 'dofile'
	...udio/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
```

**Comment by agilebean** [comment]
After many many new trial & errors, I found the root cause:
The script doesn't run if directory consistencyChecker is not compiled manually.
So in this directory, just run `make`.
Hint to the author: This is really a wonderful package - can you just update the documentation for hints like "compile the consistencyChecker directory with make"?
That would dramatically ease the pain of getting it to run...

**Comment by manuelruder** [comment]
This should be done automatically, [see here](https://github.com/manuelruder/fast-artistic-videos/blob/master/makeOptFlow_deepflow.sh#L16). And it worked for me (Ubuntu 16.04 LTS). You could check what prevented it from compiling automatically on your system, then I could incorporate a fix for this.

**Comment by agilebean** [comment]
Hm...you're right! 
Sorry, I tried to reproduce it but couldn't after reinstalling everything.
I will do this again a couple of times in the next days as I want to automatize the process for setting up a vm in the google cloud automatically. If I come across it again, I will let you know. Thanks so far.
