### ISSUE TITLE
stylizeVideo_deepflow.sh crashes calling BilinearSamplerBDHW field

### ISSUE THREAD

**Issue by agilebean** [manuelruder/fast-artistic-videos#5]
On Ubuntu 16.04 LTS, trying to stylize a video called "01rudy.mp4" by:

`bash stylizeVideo_deepflow.sh ../videos/01rudy.mp4 ./models/checkpoint-mosaic-video.t7`

This works for generating the frame*.ppm files, the flow_default directory with the forward_*.flo, backward_*.flo, reliable_*.flo files.
However, the script crashes when generating the first png file names out-00001.png. 
Why?

Here's the stack output:

```
...
Starting optical flow computation as a background task...
Starting video stylization...
Model loaded.
Elapsed time for stylizing frame independently:0.524191
Writing output image to 01rudy/out-00001.png
Waiting for file "01rudy/flow_default/reliable_2_1.pgm"

/home/rstudio/torch/install/bin/luajit: ./fast_artistic_video/utils.lua:143: attempt to call field 'BilinearSamplerBDHW' (a nil value)
stack traceback:
	./fast_artistic_video/utils.lua:143: in function 'warp_image'
	fast_artistic_video.lua:156: in function 'func_make_last_frame_warped'
	./fast_artistic_video_core.lua:162: in function 'run_next_image'
	./fast_artistic_video_core.lua:208: in function 'run_fast_neural_video'
	fast_artistic_video.lua:187: in function 'main'
	fast_artistic_video.lua:192: in main chunk
	[C]: in function 'dofile'
	...udio/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
```

**Comment by manuelruder** [comment]
Have you compiled and installed BilinearSamplerBDHW as outlined in the description?
If yes, I have no idea why it was not found. It worked for me and many others.
For a quick fix, you could change the [warp_image function in utilities.lua](https://github.com/manuelruder/fast-artistic-videos/blob/master/fast_artistic_video/utils.lua#L141) and switch to CPU warping altogether. (by removing everything in that function but line 147).

**Comment by agilebean** [comment]
After many trial & errors, I reinstalled everything and the problem disappeared.
It seems unrelated but the last action I did before stnbhwd worked was installing cunn again,
this time by
`luarocks install cunn`
instead of 
`luarocks make rocks/cunn-scm-1.rockspec`
