### ISSUE TITLE
th fast_artistic_video.lua crashes on reading backward_*.flo file

### ISSUE THREAD

**Issue by agilebean** [manuelruder/fast-artistic-videos#6]
On Ubuntu 16.04 LTS, trying to stylize a video called "01rudy.mp4" by:

`th fast_artistic_video.lua  -gpu 0 -model_vid ./models/checkpoint-mosaic-video.t7 -model_img ./models/checkpoint-mosaic-image.t7 -input_pattern  01rudy/frame_%05d.ppm -flow_pattern 01rudy/flow_default/backward_[%d]_{%d}-%d.flo -occlusions_pattern 01rudy/flow_default/reliable_[%d]_{%d}.pgm -output_prefix 01rudy`

The output video directory contains  the frame*.ppm files, the flow_default directory with the forward_*.flo, backward_*.flo, reliable_*.flo files.
However, the script crashes when reading the first backward_*.flo file.
Why?

Here's the stack output:

```

Model loaded.
Model loaded.
Elapsed time for stylizing frame independently:0.369105
Writing output image to 01rudy/out-00001.png
/home/rstudio/torch/install/bin/luajit: cannot open <01rudy/flow_default/backward_2_1-1496952976.flo> in mode r  at /tmp/luarocks_torch-scm-1-4820/torch7/lib/TH/THDiskFile.c:673
stack traceback:
	[C]: at 0x7fdd59363440
	[C]: in function 'DiskFile'
	./flowFileLoader.lua:15: in function 'load'
	fast_artistic_video.lua:155: in function 'func_make_last_frame_warped'
	./fast_artistic_video_core.lua:162: in function 'run_next_image'
	./fast_artistic_video_core.lua:208: in function 'run_fast_neural_video'
	fast_artistic_video.lua:187: in function 'main'
	fast_artistic_video.lua:192: in main chunk
	[C]: in function 'dofile'
	...udio/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
```

**Comment by manuelruder** [comment]
You are not stylizing a VR video, so you only need two placeholders for the flow. e.g. `backward_[%d]_{%d}.flo`

**Comment by agilebean** [comment]
That solved it.
Thank you!!!
